"""empty message

Revision ID: 15b5dfab5df1
Revises: 
Create Date: 2020-04-28 15:22:42.934459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15b5dfab5df1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('setter_username', sa.String(length=64), nullable=True),
    sa.Column('q1', sa.String(length=512), nullable=True),
    sa.Column('q2', sa.String(length=512), nullable=True),
    sa.Column('q3', sa.String(length=512), nullable=True),
    sa.Column('a1', sa.String(length=16384), nullable=True),
    sa.Column('a2', sa.String(length=16384), nullable=True),
    sa.Column('a3', sa.String(length=16384), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aid', sa.Integer(), nullable=True),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('imglink', sa.String(length=140), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('submitted', sa.Boolean(), nullable=True),
    sa.Column('evaluated', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('imglink')
    )
    op.create_index(op.f('ix_submissions_aid'), 'submissions', ['aid'], unique=False)
    op.create_index(op.f('ix_submissions_uid'), 'submissions', ['uid'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('teacher', sa.Boolean(), nullable=True),
    sa.Column('about_me', sa.String(length=140), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('association',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('asgn_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asgn_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['assignment.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'asgn_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_submissions_uid'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_aid'), table_name='submissions')
    op.drop_table('submissions')
    op.drop_table('assignment')
    # ### end Alembic commands ###
