"""Adding assignment model

Revision ID: 3549d1877acc
Revises: 1781d8402289
Create Date: 2020-04-27 06:11:32.230998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3549d1877acc'
down_revision = '1781d8402289'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('setter_username', sa.String(length=64), nullable=True),
    sa.Column('q1', sa.String(length=512), nullable=True),
    sa.Column('q2', sa.String(length=512), nullable=True),
    sa.Column('q3', sa.String(length=512), nullable=True),
    sa.Column('a1', sa.String(length=16384), nullable=True),
    sa.Column('a2', sa.String(length=16384), nullable=True),
    sa.Column('a3', sa.String(length=16384), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('association',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('asgn_id', sa.Integer(), nullable=False),
    sa.Column('submitted', sa.Boolean(), nullable=True),
    sa.Column('imagelink', sa.String(length=140), nullable=True),
    sa.ForeignKeyConstraint(['asgn_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['assignment.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'asgn_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association')
    op.drop_table('assignment')
    # ### end Alembic commands ###
